version: "3.8"
services:
  api:
    build: ./api/
    command: sh -c "while <dev/tcp/mysql/3306; do sleep 1s; done; gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 5000:8000
    restart: 
      always
    depends_on:
      - mysql
    networks:
      - globalnetwork

  web:
    build: ./web/
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./web:/app
    networks:
      - globalnetwork

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
    - ./web/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
    depends_on:
    - web
    networks:
      - globalnetwork

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - '3306:3306'
    networks:
      - globalnetwork

networks:
  globalnetwork:

volumes:
  mysql:
    external: true